spring:
   kafka:
      bootstrap-servers: localhost:9092
      
      consumer:
         group-id: kafka-intro
      
      producer:
         key-serializer: org.apache.kafka.common.serialization.StringSerializer
         value-serializer: org.springframework.kafka.support.serializer.JsonSerializer        
         key-deserializer: org.apache.kafka.common.deserialization.StringSerializer
         value-deserializer: org.springframework.kafka.support.deserializer.JsonSerializer